#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def isEven(num):
    return num % 2 == 0

def sumOfEvenFibbonacciNumbers(upperLimit):
    currentFib = 1
    previousFib = 1    
    sumOfEvenFibs = 0
    while currentFib < upperLimit:
        if isEven(currentFib):
            sumOfEvenFibs += currentFib
        currentFib, previousFib = currentFib + previousFib, currentFib
    return sumOfEvenFibs

print sumOfEvenFibbonacciNumbers(4000000)
